# Generated by Django 2.2.6 on 2019-12-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(default='0682932790', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Groningen', max_length=50)),
                ('street', models.CharField(default='Albertine', max_length=50)),
                ('number', models.CharField(default='1', max_length=10)),
                ('postal_code', models.CharField(default='9717EV', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_detail',
            fields=[
                ('license_number', models.CharField(default='ABC123', max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Mark', max_length=30)),
                ('last_name', models.CharField(default='Twen', max_length=30)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('N', 'non binary')], default='N', max_length=1)),
                ('birth_date', models.DateTimeField()),
                ('mobile_number', models.CharField(default='0682932790', max_length=15, unique=True)),
                ('city', models.CharField(default='Groningen', max_length=50)),
                ('street', models.CharField(default='Albertine', max_length=50)),
                ('number', models.CharField(default='1', max_length=10)),
                ('postal_code', models.CharField(default='9717EV', max_length=6)),
                ('hire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model_detail',
            fields=[
                ('model_name', models.CharField(default='The car', max_length=50, primary_key=True, serialize=False)),
                ('max_capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi_detail',
            fields=[
                ('license_plate', models.CharField(default='ABC123', max_length=8, primary_key=True, serialize=False)),
                ('manufacture_year', models.IntegerField(default=2000)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('taxi_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Taxi_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start_time', models.DateTimeField()),
                ('date_end_time', models.DateTimeField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Driver')),
                ('taxi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Taxi')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('salary', models.IntegerField(default=0)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('completed', 'completed'), ('cancelled', 'cancelled'), ('process', 'process'), ('reserved', 'reserved')], default='process', max_length=10)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_people', models.IntegerField(default=1)),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
                ('from_city', models.CharField(default='Groningen', max_length=50)),
                ('from_street', models.CharField(default='Albertine', max_length=50)),
                ('from_number', models.CharField(default='1', max_length=5)),
                ('to_city', models.CharField(default='Groningen', max_length=50)),
                ('to_street', models.CharField(default='Albertine', max_length=50)),
                ('to_number', models.CharField(default='1', max_length=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Client')),
                ('taxi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Taxi')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Model_detail'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Driver_detail'),
        ),
    ]
