# Generated by Django 2.2.6 on 2019-12-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
