# Generated by Django 2.2.6 on 2019-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20191223_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='hire_date',
            field=models.DateField(),
        ),
    ]
