# Generated by Django 2.2.6 on 2019-12-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20191223_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='mobile_number',
            field=models.CharField(default='0682932790', max_length=15),
        ),
    ]
