# Generated by Django 2.2.6 on 2019-12-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_auto_20191223_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='to_date',
            field=models.DateField(),
        ),
    ]
